name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Atualizar animação da cobrinha
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permite que a action escreva no repositório
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: NairSantos
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e push da animação
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Atualizando a animação da cobrinha"
          git push origin output
