name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch: 

jobs:
  build:
    name: Atualizar animação da cobrinha
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Garantir que a pasta dist existe
        run: mkdir -p dist 

      - name: Gerar animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: NairSantos
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Verificar se o arquivo foi gerado
        run: ls dist  

      - name: Commit e push da animação
   
